## 👉 10-01. 순환 신경망 (Recurrent Neural Network, RNN)

* RNN(Recurrent Neural Network)은 입출력을 시퀀스 단위로 처리하는 모델임.
* 순환 신경망(Recurrent Neural Network) != 재귀 신경망(Recursive Neural Network)

## 1. 순환 신경망 (Recurrent Neural Network, RNN)

* RNN은 은닉층의 노드에서 활성화 함수를 거쳐서 나온 결과물을 출력층 뿐만 아니라 다음 은닉층으로 보내는 특징을 갖고 있음.
* '셀(cell)'은 RNN에서 다음 은닉 층으로 결과를 내보내는 역할을 수행함. '메모리 셀' 또는 'RNN 셀'이라고 부름.
* 다음 시점의 은닉층으로 보내는 값을 '은닉 상태(hidden state)'라고 부름.
* RNN에서는 입력 벡터, 출력 벡터, 은닉 상태라는 표현을 주로 사용함. 
* RNN은 '일 대 다(one-to-many)', '다 대 일(many-to-one)', '다 대 다(many-to-many)' 등의 형태로 모델을 설계할 수 있음.
* one-to-many RNN 모델의 예시로는 Image Captioning 작업이 있음. 
* many-to-one RNN 모델의 예시로는 감성 분류(Sentiment Classfication), 스팸 메일 분류(Spam Detection) 작업이 있음.
* many-to-many RNN 모델의 예시로는 챗봇, 번역기, 개체명 인식, 품사 태깅 작업이 있음.
* 입력층, 출력층, 은닉층 각각의 가중치는 모든 시점에서 동일함.

## 2. 파이썬으로 RNN 구현하기

In [1]:
import numpy as np

In [2]:
timesteps = 10
input_size = 4
hidden_size = 8

inputs = np.random.random((timesteps, input_size))

hidden_state_t = np.zeros((hidden_size, ))

In [3]:
print(inputs)

[[0.45153097 0.11022024 0.38644695 0.71720792]
 [0.05799528 0.43733124 0.75209126 0.99731622]
 [0.74218498 0.38270037 0.58772599 0.99626678]
 [0.39003887 0.88937745 0.5255719  0.73535565]
 [0.95748284 0.19019011 0.36040954 0.86117073]
 [0.66826772 0.92574159 0.5573582  0.63808638]
 [0.10003151 0.61884541 0.64006722 0.87932755]
 [0.93542428 0.84079463 0.2120408  0.63663394]
 [0.66028897 0.58579968 0.53920603 0.07958867]
 [0.41483122 0.02120487 0.41578796 0.57643109]]


In [4]:
print(hidden_state_t)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
Wx = np.random.random((hidden_size, input_size))
Wh = np.random.random((hidden_size, hidden_size))
b = np.random.random((hidden_size, ))

In [6]:
print(np.shape(Wx))
print(np.shape(Wh))
print(np.shape(b))

(8, 4)
(8, 8)
(8,)


In [7]:
total_hidden_states = []

for input_t in inputs:
    output_t = np.tanh(np.dot(Wx, input_t) + np.dot(Wh, hidden_state_t) + b)
    total_hidden_states.append(list(output_t))
    print(np.shape(total_hidden_states))
    hidden_state_t = output_t
    
total_hidden_states = np.stack(total_hidden_states, axis=0)

print(total_hidden_states)

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.88767048 0.97320745 0.88179528 0.71899061 0.95101054 0.92626686
  0.96891829 0.94171571]
 [0.99997861 0.99985074 0.99995268 0.99982217 0.99998219 0.99974413
  0.99996392 0.99999691]
 [0.99999071 0.99996176 0.99998312 0.99991317 0.99999678 0.99988183
  0.9999928  0.99999874]
 [0.99999047 0.99995969 0.99998238 0.99993796 0.99999272 0.99985398
  0.99998811 0.99999808]
 [0.99998281 0.99994404 0.99997394 0.99982906 0.99999709 0.99974853
  0.99998943 0.99999773]
 [0.99999144 0.99997586 0.99998398 0.99994911 0.9999948  0.99988112
  0.99999264 0.99999824]
 [0.99998971 0.99991277 0.99997834 0.99991566 0.99999005 0.99981996
  0.99998134 0.99999811]
 [0.99998572 0.99997465 0.999981   0.99990967 0.99999633 0.99980391
  0.9999909  0.99999742]
 [0.99997607 0.99990679 0.99994701 0.99986144 0.99998866 0.99938982
  0.99997774 0.99999315]
 [0.99996641 0.99971774 0.99993656 0.99965656 0.9999898  0.99912118
  0.99995611 0.99999399]

## 3. 파이토치의 nn.RNN()

In [8]:
import torch
import torch.nn as nn

In [9]:
input_size = 5
hidden_size = 8

In [10]:
inputs = torch.Tensor(1, 10, 5)

In [11]:
cell = nn.RNN(input_size, hidden_size, batch_first=True)

In [12]:
outputs, _status = cell(inputs)

In [13]:
print(outputs.shape)

torch.Size([1, 10, 8])


In [14]:
print(_status.shape)

torch.Size([1, 1, 8])


## 4. 깊은 순환 신경망 (Deep Recurrent Neural Network)

In [15]:
inputs = torch.Tensor(1, 10, 5)

In [16]:
cell = nn.RNN(input_size=5, hidden_size=8, num_layers=2, batch_first=True)

In [17]:
outputs, _status = cell(inputs)

In [18]:
print(outputs.shape)

torch.Size([1, 10, 8])


In [19]:
print(_status.shape)

torch.Size([2, 1, 8])


## 5. 양방향 순환 신경망 (Bidirectional Recurrent Neural Network)

* '양방향 순환 신경망(Bidirectional Recurrent Neural Network)'은 앞&뒤 시점을 모두 고려한 RNN 모델임.

In [20]:
inputs = torch.Tensor(1, 10, 5)

In [21]:
cell = nn.RNN(input_size=5, hidden_size=8, num_layers=2, batch_first=True, bidirectional=True)

In [22]:
outputs, _status = cell(inputs)

In [23]:
print(outputs.shape)

torch.Size([1, 10, 16])


In [24]:
print(_status.shape)

torch.Size([4, 1, 8])
